<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.95" />
  </ItemGroup>

  <ItemGroup>
    <None Update="can-scheme.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include=".vendor/waveshare/ControlCANFD.dll"
          Link="ControlCANFD.dll"
          CopyToOutputDirectory="PreserveNewest"
          Condition="Exists('.vendor/waveshare/ControlCANFD.dll')" />
    <None Include=".vendor/itek/kerneldlls/usbcan.dll"
          Link="kerneldlls/usbcan.dll"
          CopyToOutputDirectory="PreserveNewest"
          Condition="Exists('.vendor/itek/kerneldlls/usbcan.dll')" />
  </ItemGroup>

</Project>
